import { useState } from 'react';
import Header from '../components/Header';
import PredictionForm from '../components/PredictionForm';
import PredictionResult from '../components/PredictionResult';
import { predictReadmission } from '../services/api';
import { emptyForm, featureNames, numericFeatures } from '../services/features';

function PredictionPage() {
  const [values, setValues] = useState(emptyForm);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  function handleChange(event) {
    const { name, value } = event.target;
    setValues((current) => ({ ...current, [name]: value }));
    setResult(null);
    setError('');
  }

  function clearForm() {
    setValues(emptyForm);
    setResult(null);
    setError('');
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setError('');
    setResult(null);

    const form = event.currentTarget;
    if (!form.checkValidity()) {
      form.querySelector('.field input:invalid, .field select:invalid')?.focus();
      setError('Please complete all required fields with valid values before requesting a prediction.');
      return;
    }

    const patientData = Object.fromEntries(featureNames.map((name) => [
      name,
      numericFeatures.has(name) ? Number(values[name]) : values[name]
    ]));

    setLoading(true);
    try {
      setResult(await predictReadmission(patientData));
    } catch (requestError) {
      setError(requestError.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="app-shell">
      <Header />
      <main className="page-main">
        <div className="page-intro">
          <p className="intro-kicker">Diabetes care · Readmission risk</p>
          <h1>A clearer view of what comes next.</h1>
          <p>Estimate the likelihood of hospital readmission within 30 days using the patient’s encounter information.</p>
        </div>

        <div className="prediction-layout">
          <section className="prediction-card" aria-labelledby="form-title">
            <div className="card-heading">
              <div>
                <div className="step-indicator"><span>01</span> Patient data <i aria-hidden="true">→</i> <span className="step-muted">02</span> Prediction</div>
                <h2 id="form-title">Patient Readmission Prediction</h2>
                <p>Enter the patient's information below to estimate whether the patient is likely to be readmitted within 30 days.</p>
              </div>
              <span className="required-note"><span aria-hidden="true">*</span> Required fields</span>
            </div>

            <PredictionForm values={values} onChange={handleChange} onSubmit={handleSubmit} onClear={clearForm} loading={loading} />
            {error && <p className="error-message" role="alert">{error}</p>}

            <p className="disclaimer">
              This prediction is generated by a machine learning model and should be used as decision-support information, not as a medical diagnosis.
            </p>
          </section>
          <aside className="result-sidebar" aria-label="Prediction result">
            <PredictionResult result={result} />
          </aside>
        </div>
      </main>
      <footer className="site-footer">For clinical decision support only <span aria-hidden="true">·</span> Not a substitute for professional judgment</footer>
    </div>
  );
}

export default PredictionPage;